name: deploy ansible

# on: 
#   workflow_run:
#     workflows: ["GitHub Actions Demo"]
#     #"Node.js server image"]
#     types:
#       -completed

# on:
#   push:
#     paths:
#       - server/**
on:      
  push:
    paths-ignore:
      - 'server/**'
#       - '.github/workflows/**'

jobs:
  deployAnsible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/workflows/ansible
#     env:
#        SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
#        SSH_USER: ${{secrets.SSH_USER}}
