name: GitHub Actions Demo
on: 
  push:
    paths-ignore:
      - 'server/**'
#       - '.github/workflows/**'
      - 'p2.yml'
  
jobs:

  Scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      
      - name: Run audit
        uses: tangro/actions-audit@v1.1.44
        with:
          post-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
           
      - name: cheecking audit folder
        run: ls audit/ 
        
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Added Audit files"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
        
#       - name: Auditing  
#         uses: oke-py/npm-audit-action@v2.2.0
#         with:
#           audit_level: moderate
#           github_token: ${{secrets.TOKEN}}
#           issue_assignees: oke-py
#           issue_labels: vulnerability,test
#           dedupe_issues: true
      
#   Docker-Image-Build:
# #     needs: Scan
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
    
#     - name: Installing required dependencies
#       run: npm install
      
#     - name: Making production build
#       run: npm run build
          
#     - name: List files in the repository
#       run: |
#           ls ${{ github.workspace }}
    
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag ${{secrets.Docker_ID}}/devops-web-game
      
#     - name: List files in the repository
#       run: |
#           ls ${{ github.workspace }} -a
#     - run: docker image ls
          
#     - name: Docker Login
#       env: 
#         Docker_ID: ${{secrets.Docker_ID}}
#         Docker_PSWD: ${{secrets.Docker_PSWD}}
#       run: docker login -u $Docker_ID -p $Docker_PSWD
      
#     - name: Docker push
#       run: docker push ${{secrets.Docker_ID}}/devops-web-game

#     - run: docker image ls
