# name: Node.js server image
# on:
#   push: 
#       paths-ignore:
#         - '.github/workflows/**'
        
# defaults:
#  run:
#   working-directory: ./server
  
# jobs:
      
#   Docker-Image-Build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
    
# #     - name: Installing required dependencies
# #       run: npm install
      
# #     - name: Making production build
# #       run: npm run build
          
# #     - name: Moving to the server directory
# #       working-directory: ./server
          
#     - name: List files in the repository
#       run: |
#           ls
    
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag ${{secrets.Docker_ID}}/devops-web-game-server
      
#     - name: List files in the repository
#       run: |
#           ls ${{ github.workspace }} -a
#     - run: docker image ls
          
#     - name: Docker Login
#       env: 
#         Docker_ID: ${{secrets.Docker_ID}}
#         Docker_PSWD: ${{secrets.Docker_PSWD}}
#       run: docker login -u $Docker_ID -p $Docker_PSWD
      
#     - name: Docker push
#       run: docker push ${{secrets.Docker_ID}}/devops-web-game-server

#     - run: docker image ls  
